extern const GeoLayout flipnote_frog_Exclamation_Mark_Switch_opt1[];
extern const GeoLayout flipnote_frog_Material_Switch_opt1[];
extern const GeoLayout flipnote_frog_Material_Switch_opt2[];
extern const GeoLayout flipnote_frog_Material_Switch_opt3[];
extern const GeoLayout flipnote_frog_geo[];
extern u8 flipnote_frog_frogdefault_ci4[];
extern u8 flipnote_frog_frogdefault_ci4_pal_rgba16[];
extern u8 flipnote_frog_frogblink_ci4[];
extern u8 flipnote_frog_frogblink_ci4_pal_rgba16[];
extern u8 flipnote_frog_frogcroak1_ci4[];
extern u8 flipnote_frog_frogcroak1_ci4_pal_rgba16[];
extern u8 flipnote_frog_frogcroak2_ci4[];
extern u8 flipnote_frog_frogcroak2_ci4_pal_rgba16[];
extern Vtx flipnote_frog_Exclamation_Mark_Geometry_mesh_layer_1_vtx_0[4];
extern Gfx flipnote_frog_Exclamation_Mark_Geometry_mesh_layer_1_tri_0[];
extern Vtx flipnote_frog_Geometry_mesh_layer_4_vtx_0[4];
extern Gfx flipnote_frog_Geometry_mesh_layer_4_tri_0[];
extern Gfx mat_flipnote_frog_Invisible[];
extern Gfx mat_revert_flipnote_frog_Invisible[];
extern Gfx mat_flipnote_frog_Frog_Default[];
extern Gfx mat_revert_flipnote_frog_Frog_Default[];
extern Gfx mat_flipnote_frog_Frog_Blink[];
extern Gfx mat_revert_flipnote_frog_Frog_Blink[];
extern Gfx mat_flipnote_frog_Frog_Croak_1[];
extern Gfx mat_revert_flipnote_frog_Frog_Croak_1[];
extern Gfx mat_flipnote_frog_Frog_Croak_2[];
extern Gfx mat_revert_flipnote_frog_Frog_Croak_2[];
extern Gfx flipnote_frog_Exclamation_Mark_Geometry_mesh_layer_1[];
extern Gfx flipnote_frog_Exclamation_Mark_Geometry_mesh_layer_1_mat_override_Frog_Default_0[];
extern Gfx flipnote_frog_Geometry_mesh_layer_4[];
extern Gfx flipnote_frog_Geometry_mesh_layer_4_mat_override_Frog_Blink_0[];
extern Gfx flipnote_frog_Geometry_mesh_layer_4_mat_override_Frog_Croak_1_1[];
extern Gfx flipnote_frog_Geometry_mesh_layer_4_mat_override_Frog_Croak_2_2[];
extern Gfx flipnote_frog_material_revert_render_settings[];
