extern const GeoLayout cozies_area_1_geo[];
extern const GeoLayout cozies_dl_Room1_geo[];
extern const GeoLayout cozies_dl_Room2_geo[];
extern const GeoLayout cozies_dl_Room3_geo[];
extern const GeoLayout cozies_dl_Room4_geo[];
extern const GeoLayout cozies_area_1[];
extern const Collision cozies_area_1_collision[];
extern const u8 cozies_area_1_collision_rooms[];
extern const MacroObject cozies_area_1_macro_objs[];

extern Lights1 cozies_dl_death_lights;
extern Vtx cozies_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Cube_001_mesh_layer_1_vtx_0[115];
extern Gfx cozies_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Room1Platform_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Room1Platform_mesh_layer_1_vtx_0[14];
extern Gfx cozies_dl_Room1Platform_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Room1Platform_001_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Room1Platform_001_mesh_layer_1_vtx_0[128];
extern Gfx cozies_dl_Room1Platform_001_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Room2Platform_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Room2Platform_mesh_layer_1_vtx_0[64];
extern Gfx cozies_dl_Room2Platform_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Room3PlatformTransitionFrom1To4_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Room3PlatformTransitionFrom1To4_mesh_layer_1_vtx_0[91];
extern Gfx cozies_dl_Room3PlatformTransitionFrom1To4_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Suzanne_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Suzanne_mesh_layer_1_vtx_0[890];
extern Gfx cozies_dl_Suzanne_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Suzanne_001_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Suzanne_001_mesh_layer_1_vtx_0[41];
extern Gfx cozies_dl_Suzanne_001_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Suzanne_002_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Suzanne_002_mesh_layer_1_vtx_0[41];
extern Gfx cozies_dl_Suzanne_002_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Torus_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Torus_mesh_layer_1_vtx_0[28];
extern Gfx cozies_dl_Torus_mesh_layer_1_tri_0[];
extern Vtx cozies_dl_Room4Platform_mesh_layer_1_vtx_cull[8];
extern Vtx cozies_dl_Room4Platform_mesh_layer_1_vtx_0[39];
extern Gfx cozies_dl_Room4Platform_mesh_layer_1_tri_0[];
extern Gfx mat_cozies_dl_death[];
extern Gfx mat_cozies_dl_sm64_material_001[];
extern Gfx mat_revert_cozies_dl_sm64_material_001[];
extern Gfx cozies_dl_Cube_001_mesh_layer_1[];
extern Gfx cozies_dl_Room1Platform_mesh_layer_1[];
extern Gfx cozies_dl_Room1Platform_001_mesh_layer_1[];
extern Gfx cozies_dl_Room2Platform_mesh_layer_1[];
extern Gfx cozies_dl_Room3PlatformTransitionFrom1To4_mesh_layer_1[];
extern Gfx cozies_dl_Suzanne_mesh_layer_1[];
extern Gfx cozies_dl_Suzanne_001_mesh_layer_1[];
extern Gfx cozies_dl_Suzanne_002_mesh_layer_1[];
extern Gfx cozies_dl_Torus_mesh_layer_1[];
extern Gfx cozies_dl_Room4Platform_mesh_layer_1[];
extern Gfx cozies_dl_material_revert_render_settings[];
