extern const GeoLayout fight_platform_geo[];
extern Lights1 fight_platform_OutsideSpikes_f3d_lights;
extern Lights1 fight_platform_OutsideEdge_f3d_lights;
extern u8 fight_platform_OutsideSpikes_i8[];
extern u8 fight_platform_OutsideEdge_i8[];
extern Vtx fight_platform_spiner_mesh_layer_1_vtx_cull[8];
extern Vtx fight_platform_spiner_mesh_layer_1_vtx_0[108];
extern Gfx fight_platform_spiner_mesh_layer_1_tri_0[];
extern Vtx fight_platform_spiner_mesh_layer_1_vtx_1[40];
extern Gfx fight_platform_spiner_mesh_layer_1_tri_1[];
extern Gfx mat_fight_platform_OutsideSpikes_f3d[];
extern Gfx mat_revert_fight_platform_OutsideSpikes_f3d[];
extern Gfx mat_fight_platform_OutsideEdge_f3d[];
extern Gfx mat_revert_fight_platform_OutsideEdge_f3d[];
extern Gfx fight_platform_spiner_mesh_layer_1[];
extern Gfx fight_platform_material_revert_render_settings[];
