#include "src/game/envfx_snow.h"

const GeoLayout vcm_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcm_dl_pj74_vc_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcm_dl_pj74_vc_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vcm_dl_pj74_vc_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcm_dl_pj74_vc_002_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT_DECAL, 10566, -2398, -411, 0, -180, 0, vcm_dl_pj74_vc_003_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vcm_dl_pj74_vc_005_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, vcm_dl_pj74_vc_006_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout vcm_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -60, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, vcm_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vcm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, vcm_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
