extern Lights1 hf_scary_boo7_boom_lights;
extern u8 hf_scary_boo7_boo7_ci4[];
extern u8 hf_scary_boo7_boo7_ci4_pal_rgba16[];
extern Vtx hf_scary_boo7_Plane_005_mesh_vtx_cull[8];
extern Vtx hf_scary_boo7_Plane_005_mesh_vtx_0[4];
extern Gfx hf_scary_boo7_Plane_005_mesh_tri_0[];
extern Gfx mat_hf_scary_boo7_boom[];
extern Gfx mat_revert_hf_scary_boo7_boom[];
extern Gfx hf_scary_boo7_Plane_005_mesh[];
