extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const MacroObject sa_area_1_macro_objs[];
extern u8 sa_dl_sa2_space_ground_ci4_ci4[];
extern u8 sa_dl_sa2_space_ground_ci4_ci4_pal_rgba16[];
extern Vtx sa_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx sa_dl_Cube_mesh_layer_1_vtx_0[128];
extern Gfx sa_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_sa_dl_f3dlite_material[];
extern Gfx mat_revert_sa_dl_f3dlite_material[];
extern Gfx sa_dl_Cube_mesh_layer_1[];
extern Gfx sa_dl_material_revert_render_settings[];
