#include "src/game/envfx_snow.h"

const GeoLayout bdf_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -12512, 1253, 2111, bdf_dl__bg_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bdf_dl_bowser_stuff_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bdf_dl_bowser_stuff_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bdf_dl_bowser_stuff_001_mesh_layer_4),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 4814, 1585, -3666),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bdf_dl_bowser_stuff_003_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bdf_dl_bowser_stuff_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bdf_dl_bowser_stuff_005_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bdf_dl_bowser_stuff_006_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, -500, -156, bdf_dl_bowser_stuff_007_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 13835, -491, -2082, 0, 90, 0, bdf_dl_bowser_stuff_008_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3171, -539, -16535, 0, -90, 0, bdf_dl_bowser_stuff_009_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1666, 369, 1097, 90, 0, 0, bdf_dl_Untitled_001_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -2036, 369, -6, 90, 0, 0, bdf_dl_Untitled_002_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1666, 369, -1410, 90, 0, 0, bdf_dl_Untitled_003_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -11040, 369, -471, 90, 0, 0, bdf_dl_Untitled_004_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 6224, 362, -9617, 90, 0, 0, bdf_dl_Untitled_005_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 6601, 432, 7636, 90, 0, 0, bdf_dl_Untitled_006_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 1225, 2391, -8013, 0, -32, 0, bdf_dl_zbg_001_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 1700, 1773, 7091, 0, -59, 0, bdf_dl_zbg_002_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bdf_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_HAUNTED, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -70, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bdf_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bdf_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bdf_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bdf_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
