#include "levels/wmotr/area_1/geo.inc.c"
#include "levels/wmotr/area_2/geo.inc.c"
#include "levels/wmotr/area_3/geo.inc.c"
#include "levels/wmotr/area_4/geo.inc.c"
#include "levels/wmotr/area_5/geo.inc.c"
