extern const GeoLayout wmotr_area_1_geo[];
extern const GeoLayout wmotr_area_1[];
extern const Collision wmotr_area_1_collision[];
extern const MacroObject wmotr_area_1_macro_objs[];
extern const GeoLayout wmotr_area_2_geo[];
extern const GeoLayout wmotr_area_2[];
extern const Collision wmotr_area_2_collision[];
extern const MacroObject wmotr_area_2_macro_objs[];
extern const GeoLayout wmotr_area_3_geo[];
extern const GeoLayout wmotr_area_3[];
extern const Collision wmotr_area_3_collision[];
extern const MacroObject wmotr_area_3_macro_objs[];
extern const GeoLayout wmotr_area_4_geo[];
extern const GeoLayout wmotr_area_4[];
extern const Collision wmotr_area_4_collision[];
extern const MacroObject wmotr_area_4_macro_objs[];
extern const GeoLayout wmotr_area_5_geo[];
extern const GeoLayout wmotr_area_5[];
extern const Collision wmotr_area_5_collision[];
extern const MacroObject wmotr_area_5_macro_objs[];
extern Vtx wmotr_dl_start_area_mesh_vtx_0[687];
extern Gfx wmotr_dl_start_area_mesh_tri_0[];
extern Vtx wmotr_dl_start_area_mesh_vtx_1[3];
extern Gfx wmotr_dl_start_area_mesh_tri_1[];
extern Vtx wmotr_dl_start_area_mesh_vtx_2[162];
extern Gfx wmotr_dl_start_area_mesh_tri_2[];
extern Vtx wmotr_dl_instant_warps_mesh_vtx_0[3];
extern Gfx wmotr_dl_instant_warps_mesh_tri_0[];
extern Vtx wmotr_dl_instant_warps_mesh_vtx_1[3];
extern Gfx wmotr_dl_instant_warps_mesh_tri_1[];
extern Vtx wmotr_dl_main_silo_mesh_vtx_0[663];
extern Gfx wmotr_dl_main_silo_mesh_tri_0[];
extern Vtx wmotr_dl_main_silo_mesh_vtx_1[109];
extern Gfx wmotr_dl_main_silo_mesh_tri_1[];
extern Vtx wmotr_dl_chamber_10_mesh_vtx_0[663];
extern Gfx wmotr_dl_chamber_10_mesh_tri_0[];
extern Vtx wmotr_dl_chamber_10_mesh_vtx_1[3];
extern Gfx wmotr_dl_chamber_10_mesh_tri_1[];
extern Vtx wmotr_dl_chamber_10_mesh_vtx_2[109];
extern Gfx wmotr_dl_chamber_10_mesh_tri_2[];
extern Vtx wmotr_dl_chamber_12_mesh_vtx_0[580];
extern Gfx wmotr_dl_chamber_12_mesh_tri_0[];
extern Vtx wmotr_dl_chamber_12_mesh_vtx_1[135];
extern Gfx wmotr_dl_chamber_12_mesh_tri_1[];
extern Vtx wmotr_dl_decoration_mesh_vtx_0[12];
extern Gfx wmotr_dl_decoration_mesh_tri_0[];
extern Vtx wmotr_dl_decorationbackwards_mesh_vtx_0[12];
extern Gfx wmotr_dl_decorationbackwards_mesh_tri_0[];
extern Vtx wmotr_dl_platform_mesh_vtx_0[8];
extern Gfx wmotr_dl_platform_mesh_tri_0[];
extern Vtx wmotr_dl_skybox_mesh_vtx_0[4];
extern Gfx wmotr_dl_skybox_mesh_tri_0[];
extern Vtx wmotr_dl_skybox_mesh_vtx_1[4];
extern Gfx wmotr_dl_skybox_mesh_tri_1[];
extern Vtx wmotr_dl_skybox_mesh_vtx_2[4];
extern Gfx wmotr_dl_skybox_mesh_tri_2[];
extern Vtx wmotr_dl_skybox_mesh_vtx_3[4];
extern Gfx wmotr_dl_skybox_mesh_tri_3[];
extern Vtx wmotr_dl_skybox_mesh_vtx_4[4];
extern Gfx wmotr_dl_skybox_mesh_tri_4[];
extern Vtx wmotr_dl_skybox_mesh_vtx_5[4];
extern Gfx wmotr_dl_skybox_mesh_tri_5[];
extern Vtx wmotr_dl_skybox_mesh_vtx_6[4];
extern Gfx wmotr_dl_skybox_mesh_tri_6[];
extern Vtx wmotr_dl_skybox_mesh_vtx_7[4];
extern Gfx wmotr_dl_skybox_mesh_tri_7[];
extern Vtx wmotr_dl_skybox_mesh_vtx_8[4];
extern Gfx wmotr_dl_skybox_mesh_tri_8[];
extern Vtx wmotr_dl_skybox_mesh_vtx_9[4];
extern Gfx wmotr_dl_skybox_mesh_tri_9[];
extern Vtx wmotr_dl_skybox_mesh_vtx_10[4];
extern Gfx wmotr_dl_skybox_mesh_tri_10[];
extern Vtx wmotr_dl_skybox_mesh_vtx_11[4];
extern Gfx wmotr_dl_skybox_mesh_tri_11[];
extern Vtx wmotr_dl_skybox_mesh_vtx_12[4];
extern Gfx wmotr_dl_skybox_mesh_tri_12[];
extern Vtx wmotr_dl_skybox_mesh_vtx_13[4];
extern Gfx wmotr_dl_skybox_mesh_tri_13[];
extern Vtx wmotr_dl_skybox_mesh_vtx_14[4];
extern Gfx wmotr_dl_skybox_mesh_tri_14[];
extern Vtx wmotr_dl_skybox_mesh_vtx_15[4];
extern Gfx wmotr_dl_skybox_mesh_tri_15[];
extern Vtx wmotr_dl_skybox_mesh_vtx_16[4];
extern Gfx wmotr_dl_skybox_mesh_tri_16[];
extern Vtx wmotr_dl_skybox_mesh_vtx_17[4];
extern Gfx wmotr_dl_skybox_mesh_tri_17[];
extern Vtx wmotr_dl_skybox_mesh_vtx_18[4];
extern Gfx wmotr_dl_skybox_mesh_tri_18[];
extern Vtx wmotr_dl_skybox_mesh_vtx_19[4];
extern Gfx wmotr_dl_skybox_mesh_tri_19[];
extern Vtx wmotr_dl_skybox_mesh_vtx_20[4];
extern Gfx wmotr_dl_skybox_mesh_tri_20[];
extern Vtx wmotr_dl_skybox_mesh_vtx_21[4];
extern Gfx wmotr_dl_skybox_mesh_tri_21[];
extern Vtx wmotr_dl_skybox_mesh_vtx_22[4];
extern Gfx wmotr_dl_skybox_mesh_tri_22[];
extern Vtx wmotr_dl_skybox_mesh_vtx_23[4];
extern Gfx wmotr_dl_skybox_mesh_tri_23[];

extern Gfx wmotr_dl_start_area_mesh[];
extern Gfx wmotr_dl_instant_warps_mesh[];
extern Gfx wmotr_dl_main_silo_mesh[];
extern Gfx wmotr_dl_chamber_10_mesh[];
extern Gfx wmotr_dl_chamber_12_mesh[];
extern Gfx wmotr_dl_decoration_mesh[];
extern Gfx wmotr_dl_decorationbackwards_mesh[];
extern Gfx wmotr_dl_platform_mesh[];
extern Gfx wmotr_dl_skybox_mesh[];
extern Gfx wmotr_dl_material_revert_render_settings[];

