#include "src/game/envfx_snow.h"

const GeoLayout luigi_npc_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eye_half_v4_001_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_npc_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v4_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_npc_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_7___eye_X_v4_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_npc_capless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_002_switch_option_head__no_cap__mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, luigi_npc_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, luigi_npc_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, luigi_npc_000_switch_opt1_switch_face_opt3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_npc_left_hand_open_luigi[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 62, 0, 0, luigi_npc_002_switch_option_right_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_npc_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_head_mesh_layer_1_mat_override_face_1___eye_half_v4_001_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_npc_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_head_mesh_layer_1_mat_override_face_2___eye_closed_v4_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_npc_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_head_mesh_layer_1_mat_override_face_7___eye_X_v4_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_npc_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 90, 90),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_npc_000_offset_pelvis_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_001_chest_skinned_mesh_layer_1),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, luigi_npc_000_offset_001_chest_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 79, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_head_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, luigi_npc_000_switch_opt0_000_switch_001_opt1),
													GEO_BRANCH(1, luigi_npc_000_switch_opt0_000_switch_001_opt2),
													GEO_BRANCH(1, luigi_npc_000_switch_opt0_000_switch_001_opt3),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_npc_capless),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 127, -51, -105, 15, -33, -133),
										GEO_OPEN_NODE(),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_001_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 127, -51, 105, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_002_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_003_left_upper_arm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 45, -9, 49, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_npc_000_offset_003_left_upper_arm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_004_left_lower_arm_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 7, luigi_npc_000_offset_004_left_lower_arm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 62, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_003_left_hand_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, luigi_npc_left_hand_open_luigi),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_006_right_upper_arm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 46, -9, -49, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_npc_000_offset_006_right_upper_arm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_007_right_lower_arm_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, -7, luigi_npc_000_offset_007_right_lower_arm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 62, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_004_right_hand_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_009_left_upper_leg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 11, -8, 34, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_npc_000_offset_009_left_upper_leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_010_left_lower_leg_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, luigi_npc_000_offset_010_left_lower_leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_011_left_foot_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, luigi_npc_000_offset_011_left_foot_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_012_right_upper_leg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 11, -8, -35, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_npc_000_offset_012_right_upper_leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_offset_013_right_lower_leg_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, luigi_npc_000_offset_013_right_lower_leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_005_right_foot_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_000_displaylist_005_right_foot_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_npc_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
