#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/hf/leveldata.inc.c"

#include "levels/hf/hf_boo/model.inc.c"
#include "levels/hf/hf_goo/model.inc.c"
#include "levels/hf/hf_crystal/model.inc.c"
#include "levels/hf/hf_crystal/collision.inc.c"
#include "levels/hf/hf_crystal_block/model.inc.c"
#include "levels/hf/hf_crystal_block/collision.inc.c"
#include "levels/hf/hf_ice/collision.inc.c"
#include "levels/hf/hf_ice/model.inc.c"
#include "levels/hf/hf_ice_pole/model.inc.c"
#include "levels/hf/hf_ice_pole/collision.inc.c"
#include "levels/hf/hf_ice_pole2/model.inc.c"
#include "levels/hf/hf_ice_pole2/collision.inc.c"
#include "levels/hf/hf_bridge_mover/collision.inc.c"
#include "levels/hf/hf_bridge_mover/model.inc.c"
#include "levels/hf/hf_bridge1/model.inc.c"
#include "levels/hf/hf_bridge1/collision.inc.c"
#include "levels/hf/hf_bridge2/collision.inc.c"
#include "levels/hf/hf_bridge2/model.inc.c"
#include "levels/hf/hf_joel/collision.inc.c"
#include "levels/hf/hf_joel/model.inc.c"
#include "levels/hf/hf_scary_boo0/model.inc.c"
#include "levels/hf/hf_scary_boo1/model.inc.c"
#include "levels/hf/hf_scary_boo2/model.inc.c"
#include "levels/hf/hf_scary_boo3/model.inc.c"
#include "levels/hf/hf_scary_boo4/model.inc.c"
#include "levels/hf/hf_scary_boo5/model.inc.c"
#include "levels/hf/hf_scary_boo6/model.inc.c"
#include "levels/hf/hf_scary_boo7/model.inc.c"
#include "levels/hf/hf_scary_boo_lines/model.inc.c"
#include "levels/hf/hf_scary_jerma/model.inc.c"