extern const GeoLayout hf_joel_geo[];
extern Lights1 hf_joel___f3d_lights;
extern u8 hf_joel___ci4[];
extern u8 hf_joel___ci4_pal_rgba16[];
extern Vtx hf_joel_joel_mesh_layer_1_vtx_cull[8];
extern Vtx hf_joel_joel_mesh_layer_1_vtx_0[338];
extern Gfx hf_joel_joel_mesh_layer_1_tri_0[];
extern Gfx mat_hf_joel___f3d[];
extern Gfx mat_revert_hf_joel___f3d[];
extern Gfx hf_joel_joel_mesh_layer_1[];
extern Gfx hf_joel_material_revert_render_settings[];
