#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/mf/leveldata.inc.c"

#include "levels/mf/mf_bf/collision.inc.c"
#include "levels/mf/mf_bf/model.inc.c"
#include "levels/mf/mf_vine/collision.inc.c"
#include "levels/mf/mf_vine/model.inc.c"
#include "levels/mf/mf_vine2/model.inc.c"
#include "levels/mf/mf_mill/collision.inc.c"
#include "levels/mf/mf_mill/model.inc.c"
#include "levels/mf/mf_help/model.inc.c"
#include "levels/mf/mf_pillar/collision.inc.c"
#include "levels/mf/mf_pillar/model.inc.c"