extern const GeoLayout meteor_a_geo[];
extern Lights1 meteor_a_asteroid_lights;
extern u8 meteor_a_FIR_O_EE_ROCK01_ci4[];
extern u8 meteor_a_FIR_O_EE_ROCK01_ci4_pal_rgba16[];
extern Vtx meteor_a_meteor_a_mesh_layer_1_vtx_cull[8];
extern Vtx meteor_a_meteor_a_mesh_layer_1_vtx_0[61];
extern Gfx meteor_a_meteor_a_mesh_layer_1_tri_0[];
extern Gfx mat_meteor_a_asteroid[];
extern Gfx mat_revert_meteor_a_asteroid[];
extern Gfx meteor_a_meteor_a_mesh_layer_1[];
extern Gfx meteor_a_material_revert_render_settings[];
