extern void scroll_sts_mat_bdf_dl__9_f3d();
extern void scroll_sts_mat_bdf_dl__8_f3d();
extern void scroll_sts_mat_bdf_dl__10_f3d();
extern void scroll_sts_mat_bdf_dl_Lava_f3d();
extern void scroll_sts_mat_bdf_dl_PlatformsWaterfallRed_f3d();
extern void scroll_sts_mat_bdf_dl_PlatformsWaterfallBlue_f3d();
extern void scroll_sts_mat_bdf_dl_PlatformsWaterfallGreen_f3d();
extern void scroll_sts_mat_bdf_dl__auto_18_f3d();
extern void scroll_bdf();
