extern const GeoLayout mtc_line_whole_geo[];
extern Lights1 mtc_line_whole_f3d_material_lights;
extern u8 mtc_line_whole__0E012050___Copy_ci4[];
extern u8 mtc_line_whole__0E012050___Copy_ci4_pal_rgba16[];
extern Vtx mtc_line_whole_Plane_001_mesh_layer_4_vtx_cull[8];
extern Vtx mtc_line_whole_Plane_001_mesh_layer_4_vtx_0[16];
extern Gfx mtc_line_whole_Plane_001_mesh_layer_4_tri_0[];
extern Gfx mat_mtc_line_whole_f3d_material[];
extern Gfx mat_revert_mtc_line_whole_f3d_material[];
extern Gfx mtc_line_whole_Plane_001_mesh_layer_4[];
extern Gfx mtc_line_whole_material_revert_render_settings[];
