extern const GeoLayout blinking_platform_geo[];
extern Lights1 blinking_platform_gray_lights;
extern Vtx blinking_platform_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx blinking_platform_Cube_mesh_layer_5_vtx_0[24];
extern Gfx blinking_platform_Cube_mesh_layer_5_tri_0[];
extern Vtx blinking_platform_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx blinking_platform_Cube_mesh_layer_1_vtx_0[150];
extern Gfx blinking_platform_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_blinking_platform_yellow[];
extern Gfx mat_revert_blinking_platform_yellow[];
extern Gfx mat_blinking_platform_gray[];
extern Gfx blinking_platform_Cube_mesh_layer_5[];
extern Gfx blinking_platform_Cube_mesh_layer_1[];
extern Gfx blinking_platform_material_revert_render_settings[];
