extern const GeoLayout yellow_platform_geo[];
extern Lights1 yellow_platform_yellow_lights;
extern Lights1 yellow_platform_gray_lights;
extern Vtx yellow_platform_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx yellow_platform_Cube_mesh_layer_5_vtx_0[24];
extern Gfx yellow_platform_Cube_mesh_layer_5_tri_0[];
extern Vtx yellow_platform_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx yellow_platform_Cube_mesh_layer_1_vtx_0[48];
extern Gfx yellow_platform_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_yellow_platform_yellow[];
extern Gfx mat_yellow_platform_gray[];
extern Gfx mat_revert_yellow_platform_gray[];
extern Gfx yellow_platform_Cube_mesh_layer_5[];
extern Gfx yellow_platform_Cube_mesh_layer_1[];
extern Gfx yellow_platform_material_revert_render_settings[];
