extern const GeoLayout mtc_line_active_geo[];
extern Lights1 mtc_line_active_f3d_material_lights;
extern u8 mtc_line_active__0E012050_ci4[];
extern u8 mtc_line_active__0E012050_ci4_pal_rgba16[];
extern Vtx mtc_line_active_Plane_001_mesh_layer_4_vtx_cull[8];
extern Vtx mtc_line_active_Plane_001_mesh_layer_4_vtx_0[16];
extern Gfx mtc_line_active_Plane_001_mesh_layer_4_tri_0[];
extern Gfx mat_mtc_line_active_f3d_material[];
extern Gfx mat_revert_mtc_line_active_f3d_material[];
extern Gfx mtc_line_active_Plane_001_mesh_layer_4[];
extern Gfx mtc_line_active_material_revert_render_settings[];
